/**
 * Style tab — visual design token configurator for an app.
 * Reads the app's src/index.css, parses CSS custom properties,
 * provides color pickers / font selectors / radius controls,
 * and writes the updated CSS back via the agent-teams API.
 */
import { useState, useEffect, useCallback } from 'react'
import { api } from './agents/lib'

interface DesignTokens {
  accent: string
  accentHover: string
  paper: string
  paperDark: string
  ink: string
  inkDark: string
  fontBody: string
  fontDisplay: string
  radius: string
}

const DEFAULTS: DesignTokens = {
  accent: '#7c3aed', accentHover: '#6d28d9',
  paper: '#ffffff', paperDark: '#0a0a0a',
  ink: '#1a1a2e', inkDark: '#e5e7eb',
  fontBody: 'Manrope', fontDisplay: 'Fraunces',
  radius: '12px',
}

const FONT_OPTIONS = ['Manrope', 'Inter', 'DM Sans', 'Outfit', 'Plus Jakarta Sans', 'Nunito', 'Poppins', 'system-ui']
const DISPLAY_FONT_OPTIONS = ['Fraunces', 'Playfair Display', 'DM Serif Display', 'Libre Baskerville', 'Merriweather', 'serif']
const RADIUS_OPTIONS = ['0px', '4px', '8px', '12px', '16px', '24px', '999px']

function parseTokens(css: string): Partial<DesignTokens> {
  const t: Partial<DesignTokens> = {}
  const get = (name: string) => css.match(new RegExp(`--${name}:\\s*([^;]+)`))?.[1]?.trim()
  t.accent = get('accent') || undefined
  t.accentHover = get('accent-hover') || undefined
  t.paper = get('paper') || undefined
  t.ink = get('ink') || undefined
  t.radius = get('radius') || undefined
  const bodyFont = css.match(/font-family:\s*'([^']+)'/)?.[1]
  if (bodyFont) t.fontBody = bodyFont
  const displayFont = css.match(/\.display-font\s*\{[^}]*font-family:\s*'([^']+)'/)?.[1]
  if (displayFont) t.fontDisplay = displayFont
  // Dark mode tokens
  const darkBlock = css.match(/\[data-theme="dark"\][^{]*\{([\s\S]*?)\}/)?.[1] ?? ''
  const getDark = (name: string) => darkBlock.match(new RegExp(`--${name}:\\s*([^;]+)`))?.[1]?.trim()
  t.paperDark = getDark('paper') || undefined
  t.inkDark = getDark('ink') || undefined
  return t
}

function generateCss(t: DesignTokens): string {
  // Derive accent-soft from accent
  const hexToRgba = (hex: string, a: number) => {
    const m = hex.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i)
    if (!m) return `rgba(124,58,237,${a})`
    return `rgba(${parseInt(m[1]!, 16)},${parseInt(m[2]!, 16)},${parseInt(m[3]!, 16)},${a})`
  }

  return `@import 'tailwindcss';

/* ProAppStore design tokens — generated by the Style tab */
:root {
  --paper: ${t.paper};
  --paper-deep: ${t.paper === '#ffffff' ? '#f7f7f7' : t.paper};
  --ink: ${t.ink};
  --ink-strong: ${t.ink};
  --muted: #6b7280;
  --accent: ${t.accent};
  --accent-hover: ${t.accentHover};
  --accent-soft: ${hexToRgba(t.accent, 0.08)};
  --line: #e5e7eb;
  --line-strong: #d1d5db;
  --panel: rgba(255, 255, 255, 0.72);
  --panel-hover: rgba(0, 0, 0, 0.03);
  --error: #dc2626;
  --success: #16a34a;
  --warning: #ca8a04;
  --shadow: 0 1px 3px rgba(0,0,0,0.06);
  --shadow-lg: 0 4px 12px rgba(0,0,0,0.08);
  --radius: ${t.radius};
  --radius-sm: ${parseInt(t.radius) > 8 ? Math.round(parseInt(t.radius) * 0.67) + 'px' : t.radius};
  color-scheme: light dark;
}

[data-theme="dark"], @media (prefers-color-scheme: dark) {
  :root {
    --paper: ${t.paperDark};
    --paper-deep: ${t.paperDark === '#0a0a0a' ? '#050505' : t.paperDark};
    --ink: ${t.inkDark};
    --ink-strong: #f9fafb;
    --muted: #9ca3af;
    --accent: ${t.accent};
    --accent-hover: ${t.accentHover};
    --accent-soft: ${hexToRgba(t.accent, 0.1)};
    --line: #2a2a3e;
    --line-strong: #3a3a52;
    --panel: rgba(20, 20, 35, 0.72);
    --panel-hover: rgba(255, 255, 255, 0.04);
    --shadow: 0 1px 3px rgba(0,0,0,0.3);
    --shadow-lg: 0 4px 12px rgba(0,0,0,0.4);
  }
}

html[data-text="sm"] { font-size: 14px; }
html[data-text="lg"] { font-size: 18px; }
html[data-text="xl"] { font-size: 20px; }

body {
  background: var(--paper);
  color: var(--ink);
  font-family: '${t.fontBody}', system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
}

.display-font { font-family: '${t.fontDisplay}', serif; }
.text-muted { color: var(--muted); }
.card { background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius); padding: 1.25rem; box-shadow: var(--shadow); }
.card:hover { border-color: var(--line-strong); box-shadow: var(--shadow-lg); }
.btn { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.5rem 1rem; border-radius: var(--radius-sm); font-size: 0.875rem; font-weight: 600; transition: all 0.15s; cursor: pointer; border: none; }
.btn-primary { background: var(--accent); color: white; }
.btn-primary:hover { background: var(--accent-hover); }
.btn-secondary { background: var(--panel); color: var(--ink); border: 1px solid var(--line); }
.btn-secondary:hover { border-color: var(--accent); color: var(--accent); }
.btn-ghost { background: transparent; color: var(--muted); }
.btn-ghost:hover { color: var(--ink); background: var(--panel-hover); }
.btn:disabled { opacity: 0.5; cursor: not-allowed; }
.input { width: 100%; padding: 0.5rem 0.75rem; border-radius: var(--radius-sm); border: 1px solid var(--line-strong); background: var(--paper); color: var(--ink); font-size: 0.875rem; }
.input:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 2px var(--accent-soft); }
.badge { display: inline-flex; align-items: center; padding: 0.125rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
.badge-accent { background: var(--accent-soft); color: var(--accent); }
.badge-success { background: rgba(22,163,106,0.1); color: var(--success); }
.badge-error { background: rgba(220,38,38,0.1); color: var(--error); }
.empty-state { text-align: center; padding: 3rem 1rem; color: var(--muted); }
.empty-state h3 { color: var(--ink); font-weight: 700; margin-bottom: 0.5rem; }
`
}

export function AppStyle({ appId, getToken }: { appId: string; getToken: () => string | null }) {
  const [tokens, setTokens] = useState<DesignTokens>({ ...DEFAULTS })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [previewTheme, setPreviewTheme] = useState<'light' | 'dark'>('light')

  const loadCss = useCallback(async () => {
    const token = getToken()
    if (!token) { setLoading(false); return }
    try {
      const r = await api(`/projects/${appId}/files/content?path=${encodeURIComponent('src/index.css')}`, token) as { content: string }
      const parsed = parseTokens(r.content)
      setTokens(prev => ({ ...prev, ...parsed }))
    } catch { /* use defaults */ }
    setLoading(false)
  }, [appId, getToken])

  useEffect(() => { loadCss() }, [loadCss])

  const save = async () => {
    const token = getToken()
    if (!token) return
    setSaving(true)
    try {
      const css = generateCss(tokens)
      // Escape backticks in CSS to prevent breaking the markdown fence
      const safeCss = css.replace(/`/g, '\\`')
      await api(`/projects/${appId}/chat`, token, {
        method: 'POST',
        body: { message: `Update the design tokens. Write this exact content to src/index.css:\n\n\`\`\`css\n${safeCss}\n\`\`\``, thread: 'build' },
      })
      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch { /* */ }
    setSaving(false)
  }

  const set = <K extends keyof DesignTokens>(k: K, v: DesignTokens[K]) => setTokens(prev => ({ ...prev, [k]: v }))

  if (loading) return <p className="py-12 text-center text-sm text-[var(--muted)]">Loading style...</p>

  return (
    <div className="max-w-4xl space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-[var(--ink)]">Design System</h2>
          <p className="text-sm text-[var(--muted)]">Configure your app's visual identity. Changes generate CSS tokens applied app-wide.</p>
        </div>
        <div className="flex items-center gap-2">
          {saved && <span className="text-xs text-[var(--success)] font-semibold">Saved! PO will apply it.</span>}
          <button onClick={save} disabled={saving} className="btn btn-primary text-xs">
            {saving ? 'Saving...' : 'Apply Style'}
          </button>
        </div>
      </div>

      <div className="grid lg:grid-cols-[1fr_320px] gap-6">
        {/* Controls */}
        <div className="space-y-5">
          {/* Colors */}
          <div className="card space-y-3">
            <h3 className="text-sm font-semibold text-[var(--ink)]">Colors</h3>
            <div className="grid grid-cols-2 gap-3">
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Accent</span>
                <div className="flex gap-2">
                  <input type="color" value={tokens.accent} onChange={e => { set('accent', e.target.value); set('accentHover', e.target.value) }}
                    className="w-8 h-8 rounded cursor-pointer border border-[var(--line)]" />
                  <input type="text" value={tokens.accent} onChange={e => set('accent', e.target.value)}
                    aria-label="Accent color"
                    className="input font-mono text-xs" />
                </div>
              </label>
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Accent hover</span>
                <div className="flex gap-2">
                  <input type="color" value={tokens.accentHover} onChange={e => set('accentHover', e.target.value)}
                    className="w-8 h-8 rounded cursor-pointer border border-[var(--line)]" />
                  <input type="text" value={tokens.accentHover} onChange={e => set('accentHover', e.target.value)}
                    aria-label="Accent hover color"
                    className="input font-mono text-xs" />
                </div>
              </label>
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Background (light)</span>
                <div className="flex gap-2">
                  <input type="color" value={tokens.paper} onChange={e => set('paper', e.target.value)}
                    className="w-8 h-8 rounded cursor-pointer border border-[var(--line)]" />
                  <input type="text" value={tokens.paper} onChange={e => set('paper', e.target.value)}
                    aria-label="Background color (light)"
                    className="input font-mono text-xs" />
                </div>
              </label>
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Background (dark)</span>
                <div className="flex gap-2">
                  <input type="color" value={tokens.paperDark} onChange={e => set('paperDark', e.target.value)}
                    className="w-8 h-8 rounded cursor-pointer border border-[var(--line)]" />
                  <input type="text" value={tokens.paperDark} onChange={e => set('paperDark', e.target.value)}
                    aria-label="Background color (dark)"
                    className="input font-mono text-xs" />
                </div>
              </label>
            </div>
          </div>

          {/* Typography */}
          <div className="card space-y-3">
            <h3 className="text-sm font-semibold text-[var(--ink)]">Typography</h3>
            <div className="grid grid-cols-2 gap-3">
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Body font</span>
                <select value={tokens.fontBody} onChange={e => set('fontBody', e.target.value)} className="input text-xs">
                  {FONT_OPTIONS.map(f => <option key={f} value={f}>{f}</option>)}
                </select>
              </label>
              <label className="space-y-1">
                <span className="text-xs text-[var(--muted)]">Display font</span>
                <select value={tokens.fontDisplay} onChange={e => set('fontDisplay', e.target.value)} className="input text-xs">
                  {DISPLAY_FONT_OPTIONS.map(f => <option key={f} value={f}>{f}</option>)}
                </select>
              </label>
            </div>
          </div>

          {/* Shape */}
          <div className="card space-y-3">
            <h3 className="text-sm font-semibold text-[var(--ink)]">Shape</h3>
            <label className="space-y-1">
              <span className="text-xs text-[var(--muted)]">Border radius</span>
              <select value={tokens.radius} onChange={e => set('radius', e.target.value)} className="input text-xs">
                {RADIUS_OPTIONS.map(r => <option key={r} value={r}>{r}{r === '999px' ? ' (pill)' : ''}</option>)}
              </select>
            </label>
          </div>
        </div>

        {/* Live preview */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold text-[var(--muted)] uppercase tracking-wide">Preview</h3>
            <div className="flex rounded-lg border border-[var(--line)] overflow-hidden">
              <button onClick={() => setPreviewTheme('light')}
                className={`px-2 py-0.5 text-[10px] font-semibold ${previewTheme === 'light' ? 'bg-[var(--accent)] text-white' : 'text-[var(--muted)]'}`}>Light</button>
              <button onClick={() => setPreviewTheme('dark')}
                className={`px-2 py-0.5 text-[10px] font-semibold ${previewTheme === 'dark' ? 'bg-[var(--accent)] text-white' : 'text-[var(--muted)]'}`}>Dark</button>
            </div>
          </div>
          <div className="rounded-xl border border-[var(--line)] overflow-hidden" style={{
            background: previewTheme === 'dark' ? tokens.paperDark : tokens.paper,
            color: previewTheme === 'dark' ? tokens.inkDark : tokens.ink,
            fontFamily: `'${tokens.fontBody}', system-ui`,
          }}>
            {/* Mini nav */}
            <div className="border-b px-3 py-2 flex items-center justify-between" style={{ borderColor: previewTheme === 'dark' ? '#2a2a3e' : '#e5e7eb' }}>
              <span className="font-bold text-sm" style={{ fontFamily: `'${tokens.fontDisplay}', serif` }}>{appId}</span>
              <div className="flex gap-1">
                <div className="w-6 h-6 rounded-full" style={{ background: tokens.accent }} />
              </div>
            </div>
            {/* Content preview */}
            <div className="p-4 space-y-3">
              <h2 className="text-lg font-bold" style={{ fontFamily: `'${tokens.fontDisplay}', serif` }}>Welcome</h2>
              <p className="text-sm opacity-60">This is how your app looks with these tokens.</p>
              <div className="flex gap-2">
                <button className="px-3 py-1.5 text-xs font-semibold text-white" style={{ background: tokens.accent, borderRadius: tokens.radius }}>Primary</button>
                <button className="px-3 py-1.5 text-xs font-semibold border" style={{ borderColor: previewTheme === 'dark' ? '#3a3a52' : '#d1d5db', borderRadius: tokens.radius, color: previewTheme === 'dark' ? tokens.inkDark : tokens.ink }}>Secondary</button>
              </div>
              <div className="border p-3 text-xs" style={{ borderColor: previewTheme === 'dark' ? '#2a2a3e' : '#e5e7eb', borderRadius: tokens.radius }}>
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold" style={{ background: `${tokens.accent}15`, color: tokens.accent }}>Badge</span>
                  <span className="opacity-50">Card component preview</span>
                </div>
              </div>
              <input type="text" placeholder="Input field" aria-label="Preview input field" className="w-full px-2 py-1 text-xs border" style={{
                borderColor: previewTheme === 'dark' ? '#3a3a52' : '#d1d5db', borderRadius: parseInt(tokens.radius) > 8 ? Math.round(parseInt(tokens.radius) * 0.67) + 'px' : tokens.radius,
                background: previewTheme === 'dark' ? tokens.paperDark : tokens.paper,
                color: previewTheme === 'dark' ? tokens.inkDark : tokens.ink,
              }} readOnly />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
